/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.gestionincidencias.view;

import com.mycompany.gestionincidencias.dao.TicketDAO;
import com.mycompany.gestionincidencias.dto.Cliente;
import com.mycompany.gestionincidencias.dto.Ticket;
import com.mycompany.gestionincidencias.dto.Usuario;
import com.mycompany.gestionincidencias.util.Util;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author sergi
 */
public class jpanel_crear_incidencia extends javax.swing.JPanel {

    Usuario usuario;

    /**
     * Creates new form jpanel_crear_incidencia
     */
    public jpanel_crear_incidencia(Usuario usuario_acceso) throws ClassNotFoundException, SQLException {
        initComponents();

        //ASIGNAMOS AL OBJETO USUARIO EL USUARIO PASADO POR PARÁMETRO
        usuario = usuario_acceso;

        //HACEMOS USO DEL MÉTODO RELLENARCLIENTES PARA RELLENAR EL COMBOBOX
        rellenarClientes();

    }

    public void rellenarClientes() throws ClassNotFoundException, SQLException {

        ResultSet rs;

        Util util = new Util();
        Connection conexion = util.CreaConexion();
        String consulta = "SELECT nombre FROM SSB_Cliente";
        PreparedStatement ps = conexion.prepareStatement(consulta);

        rs = ps.executeQuery();

        while (rs.next()) {
            //MIENTRAS HAYA DATOS AÑADIMOS ITEMS AL COMBOBOX
            combo_cliente.addItem(rs.getString("nombre"));
        }

    }

    public int getCliente(String cliente) throws ClassNotFoundException, SQLException {

        int id = 0;

        ResultSet rs;

        Util util = new Util();
        Connection conexion = util.CreaConexion();
        String consulta = "SELECT id FROM SSB_Cliente WHERE nombre=(?)";
        PreparedStatement ps = conexion.prepareStatement(consulta);

        ps.setString(1, cliente);
        rs = ps.executeQuery();

        while (rs.next()) {
            //MIENTAS HAYA DATOS, ASIGNAMOS EN ID EL ID DEL CLIENTE
            id = rs.getInt("id");
        }

        return id;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        txt_descripcion = new javax.swing.JTextField();
        combo_estado = new javax.swing.JComboBox<>();
        combo_prioridad = new javax.swing.JComboBox<>();
        combo_cliente = new javax.swing.JComboBox<>();
        btn_crear = new com.mycompany.gestionincidencias.util.MiBoton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 14)); // NOI18N
        jLabel4.setText("CREACIÓN DE INCIDENCIAS");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 200, -1));

        jLabel1.setText("Nombre:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 90, -1, -1));

        jLabel2.setText("Descripcion:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 126, -1, -1));

        jLabel3.setText("Estado:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 164, -1, -1));

        jLabel5.setText("Prioridad:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 202, -1, -1));

        jLabel6.setText("Cliente:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 240, -1, -1));
        add(txt_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 86, 189, -1));
        add(txt_descripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 122, 189, -1));

        combo_estado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Abierto", "En curso", "Cerrada" }));
        combo_estado.setSelectedItem(null);
        combo_estado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_estadoActionPerformed(evt);
            }
        });
        add(combo_estado, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 164, 100, -1));

        combo_prioridad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Baja", "Intermedia", "Alta" }));
        combo_prioridad.setSelectedItem(null);
        add(combo_prioridad, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 197, 100, -1));

        combo_cliente.setEditable(true);
        combo_cliente.setMaximumRowCount(50);
        combo_cliente.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        combo_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_clienteActionPerformed(evt);
            }
        });
        add(combo_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 235, 100, -1));

        btn_crear.setBackground(new java.awt.Color(102, 102, 102));
        btn_crear.setText("Crear");
        btn_crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_crearActionPerformed(evt);
            }
        });
        add(btn_crear, new org.netbeans.lib.awtextra.AbsoluteConstraints(248, 279, 93, 32));
    }// </editor-fold>//GEN-END:initComponents

    private void combo_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_clienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combo_clienteActionPerformed

    private void btn_crearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_crearActionPerformed
        int id_cliente = 0;

        //COMPROBAMOS SI EL COMBOBOX DE ESTADO Y PRIORIDAD ESTÁN SELECCIONADOS
        if (combo_estado.getSelectedItem().equals(null)) {
            JOptionPane.showMessageDialog(null, "Error, el campo estado está vacío", "ERROR", 0);
        } else if (combo_prioridad.getSelectedItem().equals(null)) {
            JOptionPane.showMessageDialog(null, "Error, el campo prioridad está vacío", "ERROR", 0);
        } else {

            try {
                // TODO add your handling code here:
                id_cliente = getCliente(combo_cliente.getSelectedItem().toString());
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(jpanel_crear_incidencia.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(jpanel_crear_incidencia.class.getName()).log(Level.SEVERE, null, ex);
            }

            //CREAMOS UN OBJETO TICKET QUE PASAREMOS POSTERIORMENTE AL MÉTODO INSERTAR
            Ticket ticket = new Ticket(txt_nombre.getText(), txt_descripcion.getText(), combo_estado.getSelectedItem().toString(), combo_prioridad.getSelectedItem().toString(), id_cliente);

            //INSTANCIAMOS TICKETDAO PARA REALIZAR ACCIONES
            TicketDAO ticketsdao = new TicketDAO();

            try {

                //HACEMOS USO DEL MÉTODO INSERTARTICKET PARA INSERTAR EL TICKET PASADO POR PARÁMETRO
                ticketsdao.insertarTicket(ticket, usuario);
                txt_nombre.setText("");
                txt_descripcion.setText("");

            } catch (ParseException ex) {
                Logger.getLogger(jpanel_crear_incidencia.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(jpanel_crear_incidencia.class.getName()).log(Level.SEVERE, null, ex);
            }

        }

    }//GEN-LAST:event_btn_crearActionPerformed

    private void combo_estadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_estadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combo_estadoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.mycompany.gestionincidencias.util.MiBoton btn_crear;
    private javax.swing.JComboBox<String> combo_cliente;
    private javax.swing.JComboBox<String> combo_estado;
    private javax.swing.JComboBox<String> combo_prioridad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txt_descripcion;
    private javax.swing.JTextField txt_nombre;
    // End of variables declaration//GEN-END:variables
}
