/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.gestionincidencias.view;

import com.mycompany.gestionincidencias.dao.TicketDAO;
import com.mycompany.gestionincidencias.dto.Usuario;
import com.mycompany.gestionincidencias.negocio.LogicaNegocio;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sergi
 */
public class Panel_Modificar extends javax.swing.JFrame {

    Usuario usuario_acceso;
    Usuario usuario_ant;

    /**
     * Creates new form Panel_Modificar
     */
    public Panel_Modificar(Usuario usuario_acceso) {
        initComponents();

        //IDENTIFICAMOS EL USUARIO QUE SE HA PASADO POR PARÁMETRO EN EL CONSTRUCTOR PARA RELIZAR ACCIONES POSTERIORES
        this.usuario_acceso = usuario_acceso;

        //INSTANCIAMOS TICKETDDAO PARA REALIZAR ACCIONES
        TicketDAO ticketsdao = new TicketDAO();

        //DEFINIMOS UN MODELO PARA UNA TABLA
        DefaultTableModel dtm = new DefaultTableModel();

        //IDENTIFICAMOS LAS COLUMNAS NECESARIAS
        dtm.setColumnIdentifiers(new String[]{"Nombre", "Especialidad", "Username", "Password", "Admin"});

        //CREAMOS UN LIST DE USUARIOS
        List<Usuario> listausuarios = null;

        try {
            //LLENAMOS EL LIST DE USUARIOS HACIENDO USO DEL MÉTODO DE TICKETDAO
            listausuarios = ticketsdao.getUsuarios();
        } catch (SQLException ex) {
            Logger.getLogger(Panel_Modificar.class.getName()).log(Level.SEVERE, null, ex);
        }

        for (Usuario usuario : listausuarios) {

            dtm.addRow(usuario.toArrayString());
        }

        jtable_usuarios.setModel(dtm);

    }

    public Panel_Modificar() {

        initComponents();

        TicketDAO ticketsdao = new TicketDAO();
        DefaultTableModel dtm = new DefaultTableModel();

        dtm.setColumnIdentifiers(new String[]{"Nombre", "Especialidad", "Username", "Password", "Admin"});

        List<Usuario> listausuarios = null;

        try {
            listausuarios = ticketsdao.getUsuarios();
        } catch (SQLException ex) {
            Logger.getLogger(Panel_Modificar.class.getName()).log(Level.SEVERE, null, ex);
        }

        for (Usuario usuario : listausuarios) {

            dtm.addRow(usuario.toArrayString());
        }

        jtable_usuarios.setModel(dtm);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_especialidad = new javax.swing.JTextField();
        txt_username = new javax.swing.JTextField();
        txt_password = new javax.swing.JPasswordField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtable_usuarios = new javax.swing.JTable();
        btn_modificar = new com.mycompany.gestionincidencias.util.MiBoton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        btn_seleccionar = new com.mycompany.gestionincidencias.util.MiBoton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jtable_usuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Especialidad", "Username", "Password", "Admin"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jtable_usuarios.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jtable_usuarios.setPreferredSize(new java.awt.Dimension(880, 64));
        jScrollPane1.setViewportView(jtable_usuarios);

        btn_modificar.setBackground(new java.awt.Color(102, 102, 102));
        btn_modificar.setText("Modificar");
        btn_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modificarActionPerformed(evt);
            }
        });

        jLabel1.setText("Nombre:");

        jLabel2.setText("Especialidad:");

        jLabel3.setText("Username:");

        jLabel4.setText("Password:");

        btn_seleccionar.setBackground(new java.awt.Color(102, 102, 102));
        btn_seleccionar.setText("SELECCIONAR");
        btn_seleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_seleccionarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(txt_username, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txt_especialidad, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(txt_password)))
                .addGap(0, 329, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 617, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(334, 334, 334)
                        .addComponent(btn_modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(286, 286, 286)
                        .addComponent(btn_seleccionar, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btn_seleccionar, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_especialidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(58, 58, 58)
                .addComponent(btn_modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modificarActionPerformed
        // TODO add your handling code here:

        //ASIGNAMOS EN VARIABLES LOS DATOS NECESARIOS DE LOS CAMPOS
        String nombre = txt_nombre.getText();
        String especialidad = txt_especialidad.getText();
        String username = txt_username.getText();
        String password = txt_password.getText();

        //INSTANCIAMOS TICKETDAO PARA REALIZAR ACCIONES
        TicketDAO ticketsdao = new TicketDAO();

        try {
            //HACEMOS USO DEL MÉTODO MODIFICARUSUARIO PARA MODIFICAR EL USUARIO CON LOS DATOS PASADOS POR PARÁMETRO
            ticketsdao.modificarUsuario(usuario_ant.getNombre(), nombre, especialidad, username, password, usuario_acceso);
        } catch (ParseException ex) {
            Logger.getLogger(Panel_Modificar.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Panel_Modificar.class.getName()).log(Level.SEVERE, null, ex);
        }

        //MOSTRAMOS UN MENSAJE POR PANTALLA PARA INDICARLE AL USUARIO QUE SE HA MODIFICADO CORRECTAMENTE
        JOptionPane.showMessageDialog(rootPane, "Usuario Modificado Correctamente");
        txt_nombre.setText("");
        txt_especialidad.setText("");
        txt_username.setText("");
        txt_password.setText("");

        //HACEMOS USO DE UN MÉTODO PARA REFRESCAR LA TABLA
        refrescarjtable();
    }//GEN-LAST:event_btn_modificarActionPerformed

    private void btn_seleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_seleccionarActionPerformed
        // TODO add your handling code here:

        //ASIGANMOS EN ROW LA CELDA SELECCIONADA DE LA TABLA
        int row = jtable_usuarios.getSelectedRow();

        usuario_ant = null;
        try {
            //ASIGNAMOS EN LA VARIABLE USUARIO EL USUARIO SELECCIONADO
            usuario_ant = LogicaNegocio.mostrarUsuarios().get(row);
        } catch (SQLException ex) {
            Logger.getLogger(Panel_Modificar.class.getName()).log(Level.SEVERE, null, ex);
        }

        //ASIGNAMOS EN LOS CAMPOS LOS DATOS NECESARIO
        txt_nombre.setText(usuario_ant.getNombre().toString());
        txt_especialidad.setText(usuario_ant.getEspecialidad().toString());
        txt_username.setText(usuario_ant.getUsuario().toString());
        txt_password.setText(usuario_ant.getContraseña().toString());

    }//GEN-LAST:event_btn_seleccionarActionPerformed

    public void refrescarjtable() {

        DefaultTableModel dtm = new DefaultTableModel();

        dtm.setColumnIdentifiers(new String[]{"Nombre", "Especialidad", "Username", "Password", "Admin"});

        List<Usuario> listausuarios = null;
        try {
            listausuarios = LogicaNegocio.mostrarUsuarios();
        } catch (SQLException ex) {
            Logger.getLogger(Panel_Modificar.class.getName()).log(Level.SEVERE, null, ex);
        }

        for (Usuario usuario : listausuarios) {

            dtm.addRow(usuario.toArrayString());

        }

        jtable_usuarios.setModel(dtm);

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Panel_Modificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Panel_Modificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Panel_Modificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Panel_Modificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Panel_Modificar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.mycompany.gestionincidencias.util.MiBoton btn_modificar;
    private com.mycompany.gestionincidencias.util.MiBoton btn_seleccionar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtable_usuarios;
    private javax.swing.JTextField txt_especialidad;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JPasswordField txt_password;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables
}
