/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.gestionincidencias.view;

import com.mycompany.gestionincidencias.dto.Cliente;
import com.mycompany.gestionincidencias.dto.Usuario;
import com.mycompany.gestionincidencias.util.Util;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author sergi
 */
public class Panel_Informe_Incidencias_Cliente extends javax.swing.JFrame {

    /**
     * Creates new form Panel_Informe_Incidencias_Cliente
     */
    public Panel_Informe_Incidencias_Cliente() {
        initComponents();

        //MÉTODO PARA RELLENAR CLIENTES EN COMBOBOX
        rellenarClientes();
    }

    public void rellenarClientes() {

        ResultSet rs;

        Util util = new Util();
        Connection conexion;
        try {
            conexion = util.CreaConexion();
            String consulta = "SELECT nombre FROM SSB_Cliente";
            PreparedStatement ps = conexion.prepareStatement(consulta);

            rs = ps.executeQuery();

            //MIENTRAS HAYA DATOS RELLENAMOS EL COMBOBOX CON LOS NOMBRES DE LOS CLIENTES
            while (rs.next()) {
                combo_clientes.addItem(rs.getString("nombre"));
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Panel_Informe_Incidencias_Cliente.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Panel_Informe_Incidencias_Cliente.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        combo_clientes = new javax.swing.JComboBox<>();
        btn_generar = new com.mycompany.gestionincidencias.util.MiBoton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btn_generar.setText("GENERAR INFORME TICKET DEL CLIENTE");
        btn_generar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_generarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(combo_clientes, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btn_generar, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(combo_clientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(btn_generar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(140, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private int getIdCliente() {
        int id = 0;

        try {

            ResultSet rs;

            Util util = new Util();
            Connection conexion = util.CreaConexion();
            String consulta = "SELECT id FROM SSB_Cliente WHERE nombre=(?)";
            PreparedStatement ps = conexion.prepareStatement(consulta);

            ps.setString(1, combo_clientes.getSelectedItem().toString());

            rs = ps.executeQuery();

            //ASIGNAMOS EN ID EL ID DEL CLIENTE SELECCIONADO PREVIAMENTE DESDE LA CONSULTA
            while (rs.next()) {
                id = rs.getInt("id");
            }

        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, "ERROR " + e.toString());

        }

        return id;
    }
    private void btn_generarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_generarActionPerformed
        // TODO add your handling code here:

        String reportResource = "./src/main/java/com/mycompany/gestionincidencias/informes/REPORT_INCIDENCIAS_POR_CLIENTE.jrxml";
        String reportCompilado = "./src/main/java/com/mycompany/gestionincidencias/informes/REPORT_INCIDENCIAS_POR_CLIENTE.jasper";
        String reportPDF = "./src/main/java/com/mycompany/gestionincidencias/informes/REPORT_INCIDENCIAS_POR_CLIENTE.pdf";
        JasperReport reporte;
        boolean compilado = true;
        Map<String, Object> params = new HashMap<String, Object>();

        params.put("CLIENT", getIdCliente());

        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection conexion = (Connection) DriverManager.getConnection("jdbc:mysql://188.164.193.188:3306/appevent_grupo3", "grupo3", "&jP9n5z54");
            if (compilado) {
                reporte = (JasperReport) JRLoader.loadObjectFromFile(reportCompilado);
            } else {
                reporte = JasperCompileManager.compileReport(reportResource);
            }
            JasperPrint informe = JasperFillManager.fillReport(reporte, params, conexion);
            JasperViewer.viewReport(informe, false);
            JasperExportManager.exportReportToPdfFile(informe, reportPDF);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(this.getClass().getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(this.getClass().getName()).log(Level.SEVERE, null, ex);
        } catch (JRException ex) {
            Logger.getLogger(this.getClass().getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_generarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Panel_Informe_Incidencias_Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Panel_Informe_Incidencias_Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Panel_Informe_Incidencias_Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Panel_Informe_Incidencias_Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Panel_Informe_Incidencias_Cliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.mycompany.gestionincidencias.util.MiBoton btn_generar;
    private javax.swing.JComboBox<String> combo_clientes;
    // End of variables declaration//GEN-END:variables
}
